sudo: required

dist: xenial

language: python

services:
  - docker

stages:
  - lint
  - test

jobs:
  include:
    - stage: lint
      env:
        - JOB=lint
        - IMAGE=cmsml/cmsml
      install:
        - docker pull $image
      script:
        - bash test/docker.sh $image "flake8 cmsml setup.py"

    - stage: test
      env:
        - JOB=test_python27
        - IMAGE=cmsml/cmsml:2.7
      install:
        - docker pull $image
      script:
        - bash test/docker.sh $image

    - stage: test
      env:
        - JOB=test_python37
        - IMAGE=cmsml/cmsml:3.7
      install:
        - docker pull $image
      script:
        - bash test/docker.sh $image

    - stage: test
      env:
        - JOB=test_python38
        - IMAGE=cmsml/cmsml:3.8
      install:
        - docker pull $image
      script:
        - bash test/docker.sh $image
